#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'happyLadybugs' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING b as parameter.
#

def happyLadybugs(b):
    x=list(b)
    count=0
    count1=0
    if len(x) == x.count("_"):
        return "YES"
    if x.count("_") == 0:
        for i in range(len(x)):
            if i==0 and len(x)!=1:
                if x[i] == x[i+1]:
                    count1+= 1
                    
            if ((i-1 >= 0)  and (i+1 < len(x))):
                if x[i]== x[i-1] or x[i]==x[i+1]:
                    count1+= 1
            if i == (len(x)-1) and len(x)!=1 :
                if x[i]==x[i-1]:
                    count1+= 1
        if count1 == len(x):
            return "YES"
        else: 
            return "NO"
            
    for i in x:
        if (x.count(i)>1):
            count+= 1
    print("count",count)
    print("_ ==" , x.count("_"))
    #count= count - x.count("_")
    print(len(x)-x.count("_"), "result")
    if x.count("_") ==1:
        if len(x)-x.count("_") == count:
            return "YES"
        else:
            return "NO"
    else:
        if len(x)== count :
            return "YES"
        else:
            return "NO"
            
            
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    g = int(input().strip())

    for g_itr in range(g):
        n = int(input().strip())

        b = input()

        result = happyLadybugs(b)

        fptr.write(result + '\n')

    fptr.close()
