#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    maxrecbreak=0
    minrecbreak=0
    maxscore=scores[0]
    minscore=scores[0]
    for i in scores:
        if i>maxscore:
            maxscore= i
            maxrecbreak+=1
        if i<minscore:
            minscore=i
            minrecbreak+=1
    return (maxrecbreak , minrecbreak) 
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
