#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    if "PM" in s:
        if "12" in s:
            return s[0:8]
            
        else: 
            time = int(s[0:2]) +12
            timestring = str(time)
            return timestring+s[2:8]
       
    else:
        if "12" in s:
            return "00" +s[2:8]
        else:
            
            return s[0:8]  
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
