#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'closestNumbers' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def closestNumbers(arr):
    arr.sort()
    diff=max(arr)
    new=[]
    for i in range(len(arr)-1):
        if arr[i+1]-arr[i] < diff:
            diff = arr[i+1]-arr[i]
    for i in range(len(arr)-1):
        if arr[i+1]-arr[i] == diff:
           # new.append(arr[i])
            #new.append(arr[i+1])
            new.extend(arr[i:i+2])
    return new
             
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
