#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'migratoryBirds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def migratoryBirds(arr):
    dica={}
    maxi=0
    x=[]
    maxi1=0
    for i in range(1,6):
        dica[i]= arr.count(i)
        if maxi< arr.count(i):
            maxi=arr.count(i)
    for i in range(1,6):
        if dica[i] == maxi:
            return i
    
    
    
    
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
